name: Java CI/CD

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Package JAR file
        run: mvn package --file ./pom.xml

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to environment
        run: echo "Deploying to environment"
        env:
          environment: production

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t devops-app-test .

      - name: Push Docker image to Docker Hub
        run: docker push devops-app-test

      - name: Install Vercel CLI
        run: npm install --global vercel@canary
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Docker image to Vercel
        run: |
          vercel deploy --prebuilt \
            --prod \
            --docker \
            --confirm \
            --token ${{ secrets.VERCEL_TOKEN }}
